Repository ICLDisco/parsec, pull requests merged in 2022-03, with the labels that each got.

#330 Doc/GitHub
  .e4s/e4s.yaml
  CHANGELOG.md
  CHANGELOG.ptg.md
  CITATION.cff
  CMakeLists.txt
  INSTALL.rst
  LICENSE.txt
  README
  README.rst
  configure
  docs/doxygen/mainpage.md
Labels: documentation, enhancement, high priority

#340 Clean strings usages in CMake.
  CMakeLists.txt
  cmake_modules/AddDocumentedFiles.cmake
  cmake_modules/CheckStructureFieldOffset.cmake
  cmake_modules/FindCython.cmake
  cmake_modules/FindGD.cmake
  cmake_modules/ParsecCompilerFlags.cmake
  docs/CMakeLists.txt
  parsec/fortran/CMakeLists.txt
Labels: enhancement

#332 Allow the runtime to compile even when PTG support is not possible.
  CMakeLists.txt
  cmake_modules/ParsecCompilePTG.cmake
  examples/CMakeLists.txt
  parsec/CMakeLists.txt
  parsec/data_dist/matrix/CMakeLists.txt
  parsec/data_dist/matrix/redistribute/CMakeLists.txt
  parsec/data_dist/matrix/redistribute/redistribute_internal.h
  parsec/data_dist/matrix/redistribute/redistribute_wrapper.c
  parsec/interfaces/ptg/ptg-compiler/CMakeLists.txt
  parsec/mca/CMakeLists.txt
  parsec/mca/device/cuda/device_cuda_module.c
  tests/CMakeLists.txt
  tests/api/CMakeLists.txt
  tests/apps/CMakeLists.txt
  tests/profiling/CMakeLists.txt
Labels: enhancement

#346 Dust off the cmake_modules
  CMakeLists.txt
  cmake_modules/FindAyudame.cmake
  cmake_modules/FindPAPI.cmake
  cmake_modules/FindTAU.cmake
  configure
  parsec/mca/pins/papi/ValidateModule.CMake
Labels: enhancement

#345 New CMake versions use MPI_ROOT to find MPI
  configure
  parsec/interfaces/ptg/ptg-compiler/CMakeLists.txt
Labels: bug

#341 Fallback using a compatible HWLOC.
  CMakeLists.txt
  cmake_modules/FindHWLOC.cmake
  cmake_modules/PaRSECConfig.cmake.in
  contrib/platforms/legacy/config.bgp
  contrib/platforms/legacy/config.darter.crayxc30
  contrib/platforms/legacy/config.inc
  contrib/platforms/legacy/config.keeneland
  contrib/platforms/legacy/config.kraken.crayxt5
  contrib/platforms/legacy/config.nautilus
  contrib/platforms/legacy/titan.crayxk7
  parsec/CMakeLists.txt
Labels: bug

#348 hotfix: compile failure when Ayudame not found
  cmake_modules/FindAyudame.cmake
Labels: bug, blocker

#349 Update issue template to make it easier to read and easier to fill-up
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature-rfc.md
Labels: documentation, enhancement

#354 Update the installation instructions
  INSTALL.rst
Labels: documentation

#352 Cleanup/ptgpp assignments
  parsec/interfaces/ptg/ptg-compiler/jdf2c.c
  parsec/profiling.c
Labels: enhancement

#347 Apply -g3 to DEBUG only, set default config to Release
  CMakeLists.txt
  cmake_modules/ParsecCompilerFlags.cmake
Labels: enhancement, question

#335 Removing hard flex/bison dependency: only devs need to run the parser
  .github/CODEOWNERS
  .github/workflows/build_cmake.yml
  CMakeLists.txt
  cmake_modules/pregen_flex_bison.cmake
  contrib/pregen_flex_bison.tar
  parsec/CMakeLists.txt
  parsec/interfaces/CMakeLists.txt
  parsec/interfaces/ptg/ptg-compiler/CMakeLists.txt
  parsec/interfaces/ptg/ptg-compiler/parsec.l
  parsec/interfaces/ptg/ptg-compiler/parsec.y
  parsec/utils/keyval_lex.l
  parsec/utils/show_help_lex.l
  tests/dsl/ptg/branching/CMakeLists.txt
Labels: enhancement

#356 Fix atomics on macosX not working properly (missing header)
  CMakeLists.txt
  parsec/bindthread.c
  parsec/include/parsec/parsec_config.h.in
  parsec/include/parsec/sys/atomic-macosx.h
  parsec/include/parsec/sys/atomic-ppc.h
  parsec/include/parsec/sys/atomic.h
  parsec/parsec.c
  parsec/parsec_hwloc.c
  parsec/profiling.c
  parsec/remote_dep.c
  tests/class/atomics.c
Labels: bug

#360 Remove never compiled in '64bit' lifo implementation
  parsec/class/lifo.h
Labels: enhancement
