Repository ICLDisco/parsec, pull requests merged in 2022-06, with the labels that each got.

#380 Attempt to backport the revamp of the communication engine
  parsec/CMakeLists.txt
  parsec/debug_marks.c
  parsec/interfaces/ptg/ptg-compiler/jdf2c.c
  parsec/parsec.c
  parsec/parsec_comm_engine.c
  parsec/parsec_comm_engine.h
  parsec/parsec_internal.h
  parsec/parsec_mpi_funnelled.c
  parsec/parsec_mpi_funnelled.h
  parsec/remote_dep.c
  parsec/remote_dep.h
  parsec/remote_dep_mpi.c
  tests/dsl/dtd/CMakeLists.txt
  tests/dsl/dtd/dtd_test_ce.c
Labels: enhancement

#379 Hash table: count used buckets only when needed
  parsec/class/parsec_hash_table.c
Labels: enhancement

#386 Print the debug rank from device_show_statistics
  parsec/mca/device/device.c
Labels: bug

#351 Handle error in CUDA/HIP module init and configurable max_streams
  parsec/mca/device/cuda/device_cuda_component.c
  parsec/mca/device/cuda/device_cuda_internal.h
  parsec/mca/device/cuda/device_cuda_module.c
  parsec/mca/device/device_gpu.c
  parsec/mca/device/device_gpu.h
  tests/dsl/dtd/dtd_test_cuda_task_insert.c
Labels: bug

#387 Make the PUSHOUT and other DTD GPU concepts generic
  parsec/interfaces/dtd/insert_function.c
  parsec/interfaces/dtd/insert_function.h
  parsec/interfaces/dtd/insert_function_internal.h
  tests/dsl/dtd/dtd_bench_simple_gemm.c
Labels: bug, high priority

#381 Workaround current CUDA/HIP "solution suspicious" bug...
  parsec/mca/device/cuda/device_cuda_module.c
Labels: bug, blocker
