Repository ICLDisco/parsec, pull requests merged in 2024-11, with the labels that each got.

#697 bugfix: dtd would not run cpu hooks when compiled with cuda
  parsec/mca/device/device.c
Labels: blocker

#699 v4.0.2411 changelog
  CHANGELOG.md
  INSTALL.rst
Labels: documentation, high priority

#704 Bring back support for MPI allow_overtake
  parsec/parsec_mpi_funnelled.c
Labels: bug

#705 Fix function name for parsec_atomic_fetch_add_int64
  parsec/include/parsec/sys/atomic-x86_64.h
Labels: bug
